sudo: true

addons:
  apt:
    sources:
      - duggan-bats
    packages:
    - git
    - curl
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - build-essential
    - bats

script:
  - bats test/bats
